# Dockerfile.sonarqube
FROM gradle:7.6.1-jdk11

# Set working directory
WORKDIR /app

# Copy project files into the container
COPY . .

# Stop any running Gradle daemons
RUN gradle --stop

# Set the entrypoint to run SonarQube analysis
CMD ["./gradlew", "sonarqube", "-Dsonar.host.url=http://172.18.0.1:9000"]